get:
  description: Retrieves a list of the failed deployments
  responses:
    '200':
      description: Failed deployments list
      content:
        application/json; charset=utf-8:
          schema:
            type: string
          example:
            $ref: ./examples/200-failed-deployments.json
