get:    
  operationId: getAllDeployments
  summary: List all deployments stored in the content server  
  description: >-
    This endpoint will return a complete list of the existing deployments 
    in the Content Server. The result can be filterd using any of the optional 
    query parameters in order to get a more specific result.  
  parameters:
    - in: query
      name: from
      schema:
        type: integer
        example: 1606829553969
      description: >-
        Acts as a filter in the collection of deployments, this value is the
        minimum value of timestamp (of the field indicated by SortingField:
        localTimestamp is the default) that any deployment in the collection
        will have.
    - in: query
      name: to
      schema:
        type: integer
        example: 1606829553969
      description: >-
        Acts as a filter in the collection of deployments, this value is the
        maximum value of timestamp (of the field indicated by SortingField:
        localTimestamp is the default) that any deployment in the collection
        will have.
    - in: query
      name: entityType
      schema:
        type: string
        enum:
          - profile
          - scene
          - wearable
        example: profile
      description: >-
        The type of entities that will be shown in the collection, many values
        can be sent. If any string ends with an ‘s’ or has whitespaces, then it
        will be correctly parsed. If any of the entity types sent is invalid,
        then the request will return a 404 status code
    - in: query
      name: entityId
      schema:
        type: string
        example: QmNknKv8MuKbfZ73z4QdUEsNbTd1ZAN1fSuwTFGiNGeCt5,FhdJnKv8MuKbfZ73z4QdUEsNbTd1ZAN1fSuwTFGiNGeCm7
      description: >- 
        Comma-separted list of deployment object hashes. You can specify just
        one or many. 
    - in: query
      name: onlyCurrentlyPointed
      schema:
        type: boolean
        example: true
      description: >-
        Enable this filter to remove from the view the deployments that have
        been deleted by a new one.
    - in: query
      name: deployedBy
      schema:
        type: string
        example: '0xdbd3b0f6a8a9eb2bb5d968d26e5565a4448'
      description: >-
        The ethAddress associated with the deployment. As an example, this
        filter could be used to obtain deployments from the same user.
    - in: query
      name: sortingField
      schema:
        type: string
        enum:
          - local_timestamp
          - entity_timestamp
        example: local_timestamp
      description: >-
        This value is used as the field to order all the deployments in the
        collection. If no parameter is sent, then the default field to order
        with will be local_timestamp.
    - in: query
      name: pointer
      schema:
        type: array
        example: '106,-33'
      description: >-
        The pointer corresponding to the entity. For example, if the entity type
        is an scene, then the pointer will be a coordenate. If the entity type
        is a profile, then the pointer will be an ethAddress.
    - in: query
      name: limit
      schema:
        type: integer
        example: 100
      description: >-
        The deployments are a paginated collection, this parameter corresponds
        to the limit for each page.
    - in: query
      name: lastId
      schema:
        type: string
        example: QmNknKv8MuKbfZ73z4QdUEsNbTd1ZAN1fSuwTFGiNGeCt5
      description: >-
        It is the last entity id that was visited, so it will be skipped when
        showing current page.
    - in: query
      name: fields
      schema:
        type: string
        enum:
          - content
          - pointers
          - metadata
          - auditInfo
        example: content
      description: Fields that will be shown from the deployment.      
  responses:
    '200':
      description: List of deployments
      content:
        application/json; charset=utf-8:
          schema:
            type: object
          example:
            summary: request with limit=2
            $ref: ../../components/examples/content/200-deployments.json
    '400':
      description: Bad request
      content:
        application/json; charset=utf-8:          
          examples:
            entityType:
              summary: EntityType not recognized
              value: Found an unrecognized entity type
            offset:
              summary: Wrong offset value
              value: >-
                Offset can't be higher than 5000. Please use the 'next' property
                for pagination.
            sortingField:
              summary: Sorting field not found
              value: Found an unrecognized sort field param
            sortingOrder:
              summary: Sorting order not recognized
              value: Found an unrecognized sort order param
            timeRange:
              summary: Bad filtering
